# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import sumbangan.models


class Migration(migrations.Migration):

    dependencies = [
        ('sumbangan', '0002_permintaansumbangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemberiansumbangan',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permintaansumbangan',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pemberiansumbangan',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='pemberiansumbangan',
            name='no_telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='permintaansumbangan',
            name='alasan',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='permintaansumbangan',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, upload_to=sumbangan.models.alasan_directory_path),
        ),
        migrations.AlterField(
            model_name='permintaansumbangan',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='permintaansumbangan',
            name='no_telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
