# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import sumbangan.models


class Migration(migrations.Migration):

    dependencies = [
        ('sumbangan', '0003_auto_20170403_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemberiansumbangan',
            name='bukti_transfer',
            field=models.ImageField(blank=True, max_length=500, upload_to=sumbangan.models.bukti_transfer_directory_path),
        ),
    ]
