# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumbangan', '0004_auto_20170403_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiSumbangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=65)),
                ('jenis', models.CharField(choices=[('Pemberian', 'Pemberian'), ('Permintaan', 'Permintaan')], default='Pemberian', max_length=50)),
                ('pemberian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumbangan.PemberianSumbangan')),
                ('permintaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumbangan.PermintaanSumbangan')),
            ],
        ),
    ]
