# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumbangan', '0005_transaksisumbangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksisumbangan',
            name='pemberian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sumbangan.PemberianSumbangan'),
        ),
        migrations.AlterField(
            model_name='transaksisumbangan',
            name='permintaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sumbangan.PermintaanSumbangan'),
        ),
    ]
